const express = require('express')
const router = express.Router()
const {sendEmailVerification,updateFirstName,updateMainPhone,updateLastName,updateEmail,getTransHistory,getProfile,getUsers,deleteUsers,getPhone, getBalance,getSearchReceiver, registerUser,updatePassword,verifyAccount,loginUser,sendEmail,updateImage} = require('../controllers/users')
const {fileUpload} = require('../middleware/upload')
const{verifyAccess} = require('../middleware/auth')
const {adminCheck} = require('../middleware/admincheck')
const {accountVerification} = require('../middleware/verification')
const {cacheAllUser,delCacheUser,getDetailUser} = require('../middleware/redis')

router
  // .get('/:id/transactions-history',verifyAccess,accountVerification,getDetailUser,getTransHistory)
  // .post('/register',registerUser,sendEmailVerification)
  // .put('/:id/updatepassword',verifyAccess,accountVerification, updatePassword)
  // .put('/verify/:sendid',verifyAccount)
  // .put('/:id/updateimage',fileUpload, updateImage)
  // .post('/login', loginUser)
  // .get('/:id/profile',verifyAccess,accountVerification,getProfile)
  // .get('/:id/balance',verifyAccess,accountVerification, getBalance)
  // .get('/:id/receiver',getSearchReceiver)
  // .delete('/:id',verifyAccess,accountVerification, adminCheck, deleteUsers)
  // .get('/',verifyAccess,accountVerification,adminCheck, getUsers)
  // .get('/:id/phone',verifyAccess,accountVerification,getPhone)
  .get('/:id/transactions-history',verifyAccess,getTransHistory)
  .post('/register',registerUser,sendEmailVerification)
  .put('/:id/updatepassword',verifyAccess,updatePassword)
  .put('/:id/updatefirstname',verifyAccess,updateFirstName)
  .put('/:id/updatephone',verifyAccess,updateMainPhone)
  .put('/:id/updatelastname',verifyAccess,updateLastName)
  .put('/:id/updateemail',verifyAccess,updateEmail)
  .put('/verify/:sendid',verifyAccount)
  .put('/:id/updateimage',verifyAccess,fileUpload, updateImage)
  .post('/login', loginUser)
  .get('/:id/profile',verifyAccess,getProfile)
  .get('/:id/balance',verifyAccess,getBalance)
  .get('/:id/receiver',verifyAccess,getSearchReceiver)
  .delete('/:id',verifyAccess,deleteUsers)
  .get('/',verifyAccess,getUsers)
  .get('/:id/phone',verifyAccess,getPhone)

module.exports = router
