const express = require('express')
const router = express.Router()
const {updatePin,updatePasswordReset,sendEmailReset,resetPassword,sendEmailVerification,topuplogic,transferlogic,getFriends,updateFirstName,updateMainPhone,updateLastName,updateEmail,getTransHistory,getProfile, getBalance,registerUser,updatePassword,verifyAccount,loginUser,updateImage} = require('../controllers/users')
const {fileUpload} = require('../middleware/upload')
const{verifyAccess} = require('../middleware/auth')
// const {adminCheck} = require('../middleware/admincheck')
const {accountVerification} = require('../middleware/verification')

router
  .get('/:id/transactions-history',verifyAccess,getTransHistory)
  .post('/register',registerUser,sendEmailVerification)
  .put('/:id/updatepassword',verifyAccess,updatePassword)
  .put('/:id/updatepin',verifyAccess,updatePin)
  .put('/reset', resetPassword, sendEmailReset)
  .put('/resetpassword', updatePasswordReset)
  .put('/:id/updatefirstname',verifyAccess,updateFirstName)
  .put('/:id/updatephone',verifyAccess,updateMainPhone)
  .put('/:id/updatelastname',verifyAccess,updateLastName)
  .put('/:id/updateemail',verifyAccess,updateEmail)
  .put('/verify/:sendid',verifyAccount)
  .put('/:id/updateimage',verifyAccess,fileUpload, updateImage)
  .post('/login', loginUser, accountVerification)
  .get('/:id/profile',verifyAccess,getProfile)
  .get('/:id/balance',verifyAccess,getBalance)
  .get('/:id/friends',verifyAccess,getFriends)
  .post('/gotransfer/:idsend/:idrec',verifyAccess,transferlogic)
  .post('/gotopup/:idrec',verifyAccess, topuplogic)

module.exports = router
